#!/usr/bin/env python3
"""Move superseded material out of the repository, reversibly.

Nothing is deleted. Everything lands under ARCHIVE with its original path preserved,
and a manifest is written so any move can be undone. Run --dry-run first.

WHAT STAYS, and why, because several of these look disposable and are not:
  SOURCE_CHECKLIST.md   the per-URL audit trail the paper promises is "released with
                        the data so any citation can be checked independently"
  findings_log.md       the evidence trail that resolves the Protocol P / crude-vs-rich
                        question; cited from tab_pilot.tex
  results/              a deliberately tracked archive of every experiment output
  descriptors/          the released registry -- the paper's central artifact
  rerun_2026-09-11/     the de-duplication run that decides the scaling claim

    python scripts/paper_fixes/archive_stale.py --dry-run
    python scripts/paper_fixes/archive_stale.py
    python scripts/paper_fixes/archive_stale.py --undo
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ARCHIVE = REPO.parent / "plant-disease-edge-archive"
MANIFEST = ARCHIVE / "MANIFEST.json"

# (repo-relative path, archive subfolder, why)
MOVES = [
    # Reader-facing explanation, kept outside the repo by request.
    ("docs/EXPLAIN_LIKE_IM_10.md", "explanations",
     "plain-language walkthrough of the whole project"),

    # Review artefacts. Useful history, not part of the deliverable.
    ("docs/paper/AUDIT_2026-09-08.md", "audits", "first deep-review pass"),
    ("docs/paper/AUDIT_2026-09-09.md", "audits", "second pass (re-audit)"),
    ("docs/paper/AUDIT_2026-09-09_pass3.md", "audits", "third pass"),
    ("docs/paper/AUDIT_2026-09-09_fresh_pdf.md", "audits", "independent PDF-mode review"),
    ("docs/paper/AUDIT_2026-09-09_fresh_issues.json", "audits", "issue bundle for the above"),
    ("logs", "audits",
     "66 committee/lane review artefacts from the automated audit runs"),

    # Superseded data. Named or dated as replaced; kept for provenance.
    ("docs/paper/wiseft_SUPERSEDED_2026-09-06.json", "superseded",
     "replaced by wiseft.json under protocol_version 2"),
    ("docs/paper/run_all_exp3_lw11.json", "superseded",
     "replaced by run_all_exp3_lw11_full.json"),
    ("docs/paper/run_2026-09-01_reference.md", "superseded",
     "reference snapshot of a build three revisions old"),

    # Backups taken during the audit passes.
    ("docs/paper/_oldbuild_backup", "backups", "pre-2026-09-08 table/figure build"),
    ("docs/paper/_backup_2026-09-10", "backups", "pre-audit-fix main.tex and tab_pilot.tex"),

    # Build outputs. Every one is regenerated by a script in this repo.
    ("docs/paper/compag_preview.pdf", "build-outputs", "regenerate by compiling tex/main.tex"),
    ("docs/paper/compag_submission.zip", "build-outputs",
     "regenerate with scripts/build_submission.py"),
    ("docs/paper/compag_submission", "build-outputs",
     "regenerate with scripts/build_submission.py"),
]

# Deleted outright: bytecode caches, regenerated on import, never worth archiving.
PURGE_GLOBS = ["**/__pycache__"]


def do_moves(dry: bool) -> list[dict]:
    done = []
    for rel, sub, why in MOVES:
        src = REPO / rel
        if not src.exists():
            print(f"  [absent ] {rel}")
            continue
        dst = ARCHIVE / sub / Path(rel).name
        print(f"  [{'would move' if dry else 'moved':10s}] {rel}  ->  {dst.relative_to(ARCHIVE.parent)}")
        if not dry:
            dst.parent.mkdir(parents=True, exist_ok=True)
            if dst.exists():
                shutil.rmtree(dst) if dst.is_dir() else dst.unlink()
            shutil.move(str(src), str(dst))
        done.append({"from": rel, "to": str(dst.relative_to(ARCHIVE)), "why": why})
    return done


def do_purge(dry: bool) -> int:
    n = 0
    for pat in PURGE_GLOBS:
        for p in REPO.glob(pat):
            if p.is_dir():
                print(f"  [{'would purge' if dry else 'purged':11s}] {p.relative_to(REPO)}")
                if not dry:
                    shutil.rmtree(p, ignore_errors=True)
                n += 1
    return n


def undo() -> int:
    if not MANIFEST.exists():
        raise SystemExit(f"no manifest at {MANIFEST}; nothing to undo")
    entries = json.loads(MANIFEST.read_text(encoding="utf-8"))["moves"]
    for e in reversed(entries):
        src, dst = ARCHIVE / e["to"], REPO / e["from"]
        if not src.exists():
            print(f"  [absent] {e['to']}")
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(src), str(dst))
        print(f"  [restored] {e['from']}")
    print(f"\nrestored {len(entries)} item(s)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--undo", action="store_true")
    args = ap.parse_args()

    if args.undo:
        return undo()

    print(f"archive root: {ARCHIVE}\n")
    print("MOVES")
    moved = do_moves(args.dry_run)
    print("\nPURGE (deleted, regenerated on import)")
    n = do_purge(args.dry_run)

    if not args.dry_run:
        ARCHIVE.mkdir(parents=True, exist_ok=True)
        MANIFEST.write_text(json.dumps(
            {"repo": str(REPO), "moves": moved, "purged_pycache_dirs": n},
            indent=2), encoding="utf-8")
        (ARCHIVE / "README.md").write_text(
            "# plant-disease-edge — archive\n\n"
            "Material moved out of the repository to keep it clean. Nothing here is needed to\n"
            "build the paper or reproduce a result; everything is either history, a backup, or\n"
            "a build output that a script regenerates.\n\n"
            "`MANIFEST.json` records where each item came from.\n"
            "`python scripts/paper_fixes/archive_stale.py --undo` puts it all back.\n\n"
            "| folder | what it holds |\n|---|---|\n"
            "| `explanations/` | plain-language write-ups of the project |\n"
            "| `audits/` | review passes over the manuscript, and their raw artefacts |\n"
            "| `superseded/` | data files replaced by a later run |\n"
            "| `backups/` | snapshots taken before a bulk edit |\n"
            "| `build-outputs/` | the compiled PDF and submission package |\n",
            encoding="utf-8")

    print(f"\n{len(moved)} item(s) {'would move' if args.dry_run else 'moved'}, "
          f"{n} cache dir(s) {'would be purged' if args.dry_run else 'purged'}")
    if not args.dry_run:
        print(f"manifest: {MANIFEST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
