#!/usr/bin/env python3
"""Apply the 2026-09-10 audit fixes to the manuscript source.

Every edit is an exact-string replacement guarded by an assertion: if an anchor is
missing or ambiguous the script aborts before writing anything, so a stale anchor can
never produce a silent no-op or a half-applied patch. Re-running after a successful
pass is a no-op (each edit checks whether its replacement is already present).

    python scripts/paper_fixes/patch_audit_2026-09-10.py --dry-run   # report only
    python scripts/paper_fixes/patch_audit_2026-09-10.py             # apply
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MAIN = ROOT / "docs" / "paper" / "tex" / "main.tex"
# tab_pilot.tex carries a "GENERATED by make_tex_tables.py -- do not edit by hand"
# header, but no generator emits it: make_tex_tables.py has no tab_pilot() function.
# It is hand-maintained, so we patch it directly and correct the misleading header.
PILOT = ROOT / "docs" / "paper" / "tex" / "tab_pilot.tex"

SOURCES = (MAIN, PILOT)

# A fact only the authors can supply. Rendered so it cannot survive a proof-read, and
# caught by scripts/paper_fixes/preflight.py before submission.
TO_SUPPLY = r"\textbf{[TO SUPPLY: %s]}"


def _squash(s: str) -> str:
    """Collapse whitespace the way LaTeX does, for wrapping-insensitive comparison."""
    return " ".join(s.split())


class Edit:
    """One exact-string replacement with a human-readable justification."""

    def __init__(self, ident: str, path: Path, old: str, new: str, why: str) -> None:
        self.ident = ident
        self.path = path
        self.old = old.strip("\n")
        self.new = new.strip("\n")
        self.why = why

    def status(self, text: str) -> str:
        # ORDER MATTERS. Several edits insert text around their anchor rather than
        # replacing it outright (C1, C3b, C4 and D1 all keep the anchor sentence and add
        # to it), so the anchor is still present after a successful pass. Testing `old`
        # first would report "apply" on a re-run and duplicate whole paragraphs. The
        # replacement is therefore the authority on whether the edit has landed.
        #
        # The test ignores line wrapping: LaTeX treats any run of whitespace as a single
        # space, so re-flowing a patched paragraph must not make this look unapplied. The
        # forward match stays exact, because the replacement has to be byte-precise.
        if _squash(self.new) in _squash(text):
            return "already"
        n_old = text.count(self.old)
        if n_old == 1:
            return "apply"
        if n_old > 1:
            raise SystemExit(
                f"[{self.ident}] anchor is ambiguous ({n_old} matches) in "
                f"{self.path.name}; narrow the anchor before re-running."
            )
        raise SystemExit(
            f"[{self.ident}] anchor not found in {self.path.name}, and the replacement "
            f"is not present either -- the source has drifted.\n"
            f"--- expected ---\n{self.old[:500]}"
        )


EDITS: list[Edit] = []


def edit(ident: str, path: Path, old: str, new: str, why: str) -> None:
    EDITS.append(Edit(ident, path, old, new, why))


# ---------------------------------------------------------------------------
# A. The 19.9 vs 27.0 conflict: two different descriptor strategies, never fenced.
#    Table 1 is the Protocol-P *crude* probe (findings_log run 5). Section 4.2 is the
#    Protocol-P *rich* bake-off (run 8, run_all_bakeoff.json). Both numbers are right;
#    the manuscript never said they use different prompt strategies.
# ---------------------------------------------------------------------------
edit(
    "A1-pilot-caption", PILOT,
    r"Pilot encoder survey (Protocol~P: 17 held-out classes, chance 5.9\%, keyword-bank descriptors).",
    r"Pilot encoder survey (Protocol~P: 17 held-out classes, chance 5.9\%, \emph{crude} "
    r"single-sentence keyword descriptors --- not the \emph{rich} symptom bank used in the "
    r"bake-off of Section~\ref{sec:bakeoff}, whose numbers are accordingly higher).",
    "Table 1 holds the crude-strategy probe but was labelled as the keyword bank (= rich).",
)

edit(
    "A1b-pilot-header", PILOT,
    r"% GENERATED by docs/paper/make_tex_tables.py -- do not edit by hand.",
    r"""% HAND-MAINTAINED. make_tex_tables.py has no tab_pilot() function, so this file is NOT
% generated despite what earlier revisions of this header claimed. Values are the
% Protocol-P crude-strategy probe (findings_log.md run 5) and are transcribed from
% make_figures.py's PROBE table. Do not confuse them with the rich-strategy bake-off
% in run_all_bakeoff.json (findings_log.md run 8), which scores the same 17 classes
% higher because it uses a different descriptor strategy.""",
    "The header claimed the file is generated; nothing generates it, which invites silent drift.",
)

edit(
    "A2-bakeoff-fence", MAIN,
    r"""The 11.4\,M encoder recovers 86\% of the 92.9\,M reference at one eighth the parameters, and
\emph{beats} the larger 21.5\,M model --- on the pilot set; on the nested splits of Table~\ref{tab:scale} the ordering reverses at every configuration, so we read this as recipe noise rather than a ranking.""",
    r"""This bake-off re-scores the Protocol-P pilot set with the \emph{rich} symptom bank, whereas the
survey of Table~\ref{tab:pilot} uses the \emph{crude} single-sentence strategy; the two are
therefore not comparable cell by cell, and every figure in this subsection is a rich-strategy
number. Under that strategy the 11.4\,M encoder reaches 27.0\% against 31.5\% for the 92.9\,M
reference --- 86\% of it at one eighth the parameters --- and \emph{beats} the larger 21.5\,M
model, which reaches 22.4\%. On the nested splits of Table~\ref{tab:scale} that ordering reverses
at every configuration, so we read it as recipe noise rather than a ranking.""",
    "Section 4.2 looked like it contradicted Table 1; it is a different descriptor strategy.",
)

edit(
    "A3-crude-label-4.1", MAIN,
    r"""a 5.5\,M student distilled from scratch reaches only 11.0\% against 5.9\% chance, versus 19.9\%
for the frozen 11.4\,M encoder it was distilled from;""",
    r"""a 5.5\,M student distilled from scratch reaches only 11.0\% against 5.9\% chance, versus 19.9\%
for the frozen 11.4\,M encoder it was distilled from (both under the \emph{crude} strategy of
Table~\ref{tab:pilot});""",
    "Anchors 19.9% to its strategy so it cannot be read against Section 4.2's 27.0%.",
)

# ---------------------------------------------------------------------------
# B. Claims contradicted by the released JSONs.
# ---------------------------------------------------------------------------
edit(
    "B1-leads-on-neither", MAIN,
    r"whereas at the smallest label space it leads on neither sweep.",
    r"""whereas at the smallest label space it still leads the top-5 sweep on three of the four but the
risk--coverage sweep on only one.""",
    "metrics_abstain_A.json: grounded leads top-5 3/4 and AURC 1/4 at config A, not neither.",
)

edit(
    "B2-drop-fragment", MAIN,
    r"the system can decline rather than guess. Selective accuracy rising with coverage,",
    r"the system can decline rather than guess.",
    "Removes a verbless fragment that also reversed the direction of the effect.",
)

edit(
    "B3-monotonicity-scope", MAIN,
    r"""confirming the confidence signal is correctly ordered rather than inverted --- a property that
holds for every encoder, every strategy and every scale we measured.""",
    r"""On the coverage grid we report --- 100\% down to 50\% in steps of ten --- selective accuracy
rises at every step in all 30 encoder/strategy/scale cells, so the confidence signal is correctly
ordered rather than inverted. The fine-grained curve is not pointwise monotone below roughly half
coverage, where the surviving sample is too small to estimate accuracy stably, so we state the
ordering on the grid the gate actually operates on.""",
    "Pointwise monotonicity fails in 19/30 curves above coverage 0.2; holds 30/30 on the reported grid.",
)

edit(
    "B4-interval-direction", MAIN,
    r"""so the largest sourcing penalty
these data exclude is about half a point on the full set and rather more on the paired
subset.""",
    r"""so these data are consistent with a
sourcing penalty as large as 0.5 points on the full set and 0.2 points on the paired subset, and
exclude only penalties larger than that.""",
    "The old sentence had it backwards: the paired bound (-0.23) is tighter, not looser.",
)

edit(
    "B5-wiseft-nonmonotone", MAIN,
    r"""Neither column is monotone in $\alpha$ --- $\alpha=0.75$ beats
$\alpha=0.25$ on both --- so the weight selects an operating point rather than sliding along
a frontier.""",
    r"""Neither column is monotone in $\alpha$ --- seen accuracy dips to 56.0\% at $\alpha=0.25$, below
the 59.0\% of the frozen endpoint, and unseen accuracy falls to 14.8\% there before recovering to
18.4\% at $\alpha=0.75$ --- so the weight selects an operating point rather than sliding along
a frontier.""",
    "The old example (0.75 beats 0.25 on both) is consistent with monotonicity and proved nothing.",
)

edit(
    "B6-contribution-2", MAIN,
    r"""\item \textbf{A nested scale study isolating what descriptor authoring actually buys.} Symptom text
beats a bare class name at every scale (+8.8 points at 16 classes for source-grounded text), and
source-grounded descriptors keep improving as the unseen label space triples.""",
    r"""\item \textbf{A nested scale study isolating what descriptor authoring actually buys.}
Source-grounded text beats a bare class name at every scale (+8.8 points at 16 classes), while a
single generic symptom sentence does not --- it loses to the bare name at 34 and 51 classes --- and
source-grounded descriptors keep improving as the unseen label space triples, a trend
Section~\ref{sec:limits} reports as provisional because it cannot yet be separated from falling
duplicate-label density.""",
    "'Symptom text beats bare at every scale' is refuted by the crude column in Section 4.3.",
)

edit(
    "B7-dedup-chance", MAIN,
    r"""removing one label from each of the five alias pairs, and four of the five non-disease
labels, leaves 42 classes and raises the grounded mean
from 23.9\% to 30.8\%. Cleaning helps the method, so reporting the uncleaned numbers as the
headline is conservative,""",
    r"""removing one label from each of the five alias pairs, and four of the five non-disease
labels, leaves 42 classes and raises the grounded mean from 23.9\% to 30.8\%. Part of that
6.9-point rise is mechanical: dropping nine classes lifts the chance floor from 1.96\% to 2.38\%,
so relative to chance the cleaned figure is 12.9$\times$ against 12.2$\times$ for the uncleaned
one, and the gain net of the smaller label space is far below 6.9 points. Cleaning still helps the
method on either reading, so reporting the uncleaned numbers as the headline is conservative,""",
    "The +6.9 was confounded by the label space shrinking from 51 to 42 classes.",
)

edit(
    "B8-scaling-qualifier-conclusion", MAIN,
    r"""The levers are, in order: the descriptor authoring method --- and
specifically the finding that source-grounded descriptors keep improving as the unseen label space
grows --- honest abstention, and the frozen-backbone hybrid.""",
    r"""The levers are, in order: the descriptor authoring method --- source-grounded text is worth
8.8 points over a bare class name at the focused scale, and is the only strategy that does not
decay as the label space triples, a trend we report as provisional because
Section~\ref{sec:limits} cannot yet separate it from falling duplicate-label density --- honest
abstention, and the frozen-backbone hybrid.""",
    "Conclusion stated the scaling claim flat while Section 6 calls it provisional.",
)

edit(
    "B9-scold-related-work", MAIN,
    r"""We evaluate the biological foundation model
BioCLIP\,2~\citep{bioclip2} and the leaf-disease model SCOLD~\citep{scold2025} as candidate backbones
and find they do not transfer competitively under our descriptor protocol: the better of the
two reaches 1.6$\times$ chance against 4.6$\times$ for a general-purpose 11.4\,M encoder
(Section~\ref{sec:bakeoff}).""",
    r"""We evaluate the biological foundation model
BioCLIP\,2~\citep{bioclip2} as a candidate backbone and find it does not transfer competitively under
our descriptor protocol, reaching 1.6$\times$ chance against 4.6$\times$ for a general-purpose
11.4\,M encoder. We also attempted the leaf-disease model SCOLD~\citep{scold2025}, but only through a
best-effort wrapper, so we report its number without resting any claim on it
(Section~\ref{sec:bakeoff}).""",
    "Related work asserted a SCOLD finding that Section 4.2 explicitly declines to claim.",
)

# ---------------------------------------------------------------------------
# C. Reproducibility disclosure the manuscript simply never states.
# ---------------------------------------------------------------------------
edit(
    "C1-protocol-definitions", MAIN,
    r"""Held-out crops
are never used for training at any stage; they are diagnosed only from descriptor text.""",
    r"""Held-out crops
are never used for training at any stage; they are diagnosed only from descriptor text.

Two evaluation protocols appear in this article and are never mixed. \emph{Protocol~N} is the
nested design just described --- configurations A, B and C at 16, 34 and 51 held-out classes ---
and it carries every headline result. \emph{Protocol~P} is an earlier pilot on a single held-out
pool, Coffee, Orange and Peach, 17 classes over 1{,}618 images at chance 5.9\%, retained because
the ten-encoder survey, the from-scratch distillation baseline and the domain-model bake-off were
run on it and have not been repeated under Protocol~N. Protocol-P numbers are never compared with
Protocol-N numbers, and each is labelled at the point of use together with the descriptor strategy
it was measured under, since the pilot was scored under both the \emph{crude} and the \emph{rich}
strategy at different times.""",
    "Protocol P/N were used throughout Results but defined nowhere.",
)

edit(
    "C2-checkpoint-tags", MAIN,
    r"""We evaluate four deployable tiers (11.4, 21.5, 35.8 and 86.3\,M image-encoder parameters) plus a
92.9\,M reference ceiling.""",
    r"""We evaluate four deployable tiers plus a reference ceiling, each pinned to one public
\texttt{open\_clip} checkpoint: MobileCLIP2-S0/\texttt{dfndr2b} (11.4\,M),
MobileCLIP-S1/\texttt{datacompdr} (21.5\,M), MobileCLIP2-S2/\texttt{dfndr2b} (35.8\,M),
MobileCLIP-B/\texttt{datacompdr} (86.3\,M) and ViT-B-16-SigLIP2/\texttt{webli} (92.9\,M, reference
only). Parameter counts are image-tower only. Because Section~\ref{sec:flat} attributes an
8.5-point spread to pretraining recipe rather than to capacity, the pretraining tag is part of the
model identity throughout and is carried in every released result file.""",
    "Checkpoint tags appeared once, in a table caption; the recipe claim needs them everywhere.",
)

edit(
    "C3-llm-disclosure", MAIN,
    r"""Records are generated by an LLM under a
strict grounding prompt that forbids un-cited claims, then audited.""",
    r"""Records are generated by Claude Sonnet 4.6 (\texttt{anthropic/claude-sonnet-4-6}) at
temperature 0 with a 2{,}000-token response budget, under a strict grounding prompt that forbids
un-cited claims, then audited. The full
prompt, the decoding parameters and the seven generation seeds used by the control arm of
Section~\ref{sec:strategies} are released with the descriptor registry, so the registry can be
regenerated end to end.""",
    # Values read from scripts/build_descriptors.py:232 (LAVA_MODEL default
    # "anthropic/claude-sonnet-4-6", temperature=0.0) and :54 (MAX_TOKENS=2000). The control
    # arms use a DIFFERENT model and temperature -- see C3b.
    "The paper's central contribution is LLM-authored text and the generator was never named.",
)

edit(
    "C3b-control-arm-model", MAIN,
    r"""differ in exactly one instruction, the difference between them estimates the effect of sourcing
alone.""",
    r"""differ in exactly one instruction, the difference between them estimates the effect of sourcing
alone. Both control arms are generated by Claude Sonnet 5 at temperature 1 with a per-seed sampling
seed --- a newer model and a higher temperature than the shipped registry of
Section~
ef{sec:desc-gen}, which used Claude Sonnet 4.6 at temperature 0. That is deliberate:
sampling must be stochastic for seeds to differ at all, and the grounded side of the control is
regenerated under the new settings rather than reused from the shipped registry, so the comparison
cannot confound the sourcing instruction with a change of model or decoding temperature.""",
    # scripts/build_ungrounded.py:52 (DEFAULT_MODEL "claude-sonnet-5") and :80 (temperature=1.0).
    "The control arm uses a different generator than the registry; that is deliberate and unstated.",
)

edit(
    "C4-verification-ratio", MAIN,
    r"""The
symptom text --- the string that becomes the CLIP text prototype --- is the functional component; the
verified citations provide the auditability guarantee. Records that could not be grounded""",
    r"""This verification is partial and we report its extent rather than implying completeness: of the
47 filled records on held-out crops, 23 carry at least one page-verified field, and
Section~\ref{sec:limits} gives the full breakdown. The
symptom text --- the string that becomes the CLIP text prototype --- is the functional component; the
verified citations provide the auditability guarantee. Records that could not be grounded""",
    "Methods implied the held-out diseases are verified; Section 6 reveals it is 23 of 47.",
)

edit(
    "C5-cpu-disclosure", MAIN,
    r"""Table~\ref{tab:edge} and Fig.~\ref{fig:edge} report the deployable image encoder on a laptop processor.""",
    r"""Table~\ref{tab:edge} and Fig.~\ref{fig:edge} report the deployable image encoder on a laptop
processor --- """
    + (TO_SUPPLY % "CPU model, e.g. Intel Core i7-1260P")
    + r""", 16 threads, ONNX Runtime 1.26.0, batch 1, 224\,px, median of 50 runs. We measure a laptop
CPU rather than an embedded board: the INT8 analysis of Section~\ref{sec:int8} is x86-specific, and
extending these measurements to Arm-class hardware is named as future work in
Section~\ref{sec:limits}.""",
    "17.4 ms is a headline result and no processor was ever named.",
)

# ---------------------------------------------------------------------------
# D. Scope limitations a reviewer will raise and the paper does not pre-empt.
# ---------------------------------------------------------------------------
edit(
    "D1-missing-baselines", MAIN,
    r"""\paragraph{Sub-10\,M gap}""",
    r"""\paragraph{Baselines we did not run} Three comparisons a reader may reasonably expect are absent.
We do not implement per-class descriptor generation in the DCLIP~\citep{menon2023} or
CuPL~\citep{pratt2023} form, so our evidence that per-class text avoids the bank's collisions is
indirect: the ungrounded control arm is per-class-generated and serves that role, but it was not
designed as a reimplementation of either method. Every prototype in this article is already
ensembled over three prompt templates rather than embedded from a single one, but we do not sweep
the 80-template ImageNet set that the original CLIP zero-shot recipe uses, so the bare-class-name
row is a weaker ensemble than the strongest available. And we do not report the SAGE cloud agent's accuracy on our
held-out split, so the ``deployable edge counterpart'' framing is an argument about cost and
connectivity rather than a measured accuracy comparison. Each is a run rather than a
reinterpretation, and we name them as the first additions to this benchmark.

\paragraph{Sub-10\,M gap}""",
    "No prior pass raised these; a CEA reviewer will ask for at least the prompt ensemble.",
)

edit(
    "D2-loco-terminology", MAIN,
    r"""Table~\ref{tab:loco} shows the two hardest crops overall are both \emph{trained} crops, so
difficulty is not simply a function of whether a crop was held out.""",
    r"""Table~\ref{tab:loco} scores every crop zero-shot from descriptor text on a common 78-class pool
using the \emph{rich} strategy rather than the grounded one; ``trained'' there labels crops that sit
in the seen pool of the main experiments, not crops trained on for this analysis. The two hardest
crops overall are both trained crops, so difficulty is not simply a function of whether a crop was
held out.""",
    "A leave-one-crop-out table that calls three crops 'trained' reads as a contradiction.",
)

# ---------------------------------------------------------------------------
# E. Mechanical.
# ---------------------------------------------------------------------------
edit(
    "E1-keywords", MAIN,
    r"""edge deployment \sep
source-grounded descriptors \sep
precision agriculture""",
    r"""edge deployment \sep
source-grounded descriptors""",
    "CEA allows six keywords; the list had seven.",
)

edit(
    "E2-supervised-spearman-p", MAIN,
    r"accuracy is weak (Spearman $\rho = 0.36$).",
    r"accuracy is weak and not distinguishable from no association (Spearman $\rho = 0.36$, $p = 0.21$, $n = 14$).",
    "Table 1 reports a p-value for the same statistic; Table 6 did not.",
)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true", help="report without writing")
    args = ap.parse_args()

    for p in SOURCES:
        if not p.exists():
            raise SystemExit(f"missing source file: {p}")

    texts = {p: p.read_text(encoding="utf-8") for p in SOURCES}

    # patch_rerun_2026-09-11.py rewrote the abstract and contribution 2 on top of two of
    # the edits below, so those anchors are legitimately gone. This script is a historical
    # record of what the 2026-09-10 audit changed, not a re-runnable migration; say so
    # instead of aborting with "the source has drifted", which reads like a real problem.
    if "A de-duplicated re-run at all three scales" in texts[MAIN]:
        print("SUPERSEDED: patch_rerun_2026-09-11.py has revised the scaling claim on top of\n"
              "these edits. This script is kept as the record of the 2026-09-10 pass; it is\n"
              "not re-runnable against the current source. Nothing was changed.")
        return 0

    # Resolve every edit against the ORIGINAL text before writing anything, so a late
    # failure cannot leave the tree half-patched.
    plan = [(e, e.status(texts[e.path])) for e in EDITS]

    for e, st in plan:
        if st == "apply":
            texts[e.path] = texts[e.path].replace(e.old, e.new, 1)

    applied = [e for e, s in plan if s == "apply"]
    skipped = [e for e, s in plan if s == "already"]

    if not args.dry_run:
        for p, t in texts.items():
            # newline="" prevents Windows CRLF translation. The manuscript is LF-only and
            # a previous pass shipped 1,011 CR bytes into main.tex this way.
            with open(p, "w", encoding="utf-8", newline="") as fh:
                fh.write(t)

    verb = "would apply" if args.dry_run else "applied"
    print(f"{verb} {len(applied)}/{len(EDITS)} edits; {len(skipped)} already present\n")
    for e, st in plan:
        print(f"  [{st:7s}] {e.ident:30s} {e.why}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
