"""
Emit Elsevier-ready LaTeX tables (booktabs) from the SAME result JSONs make_tables.py reads.

WHY: the manuscript is tex/main.tex and its tables are generated. Maintaining tables in
both by hand is how the paper drifted from the data three times. main.tex \\input{}s these files, so
there is exactly one source of truth -- the JSONs -- for every number in either format.

    python docs/paper/make_tex_tables.py      # writes docs/paper/tex/tab_*.tex
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = Path(__file__).resolve().parent
TEX = HERE / "tex"
TEX.mkdir(parents=True, exist_ok=True)


def load(name):
    p = HERE / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def pct(x, nd=1):
    return "---" if x is None else f"{x * 100:.{nd}f}\\%"


def short(n):
    return n.split("/")[0].replace("_", "-")


def write(fname, lines):
    (TEX / fname).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[tex] wrote {TEX / fname}")


def wrap(caption, label, colspec, header, body, note=None, wide=False):
    """Render one booktabs table. `wide` promotes it to table*, spanning both
    columns: an eight-column numeric table does not fit the cas-dc single-column
    measure once its headers carry units and direction markers."""
    env = "table*" if wide else "table"
    out = [
        "% GENERATED by docs/paper/make_tex_tables.py -- do not edit by hand.",
        "\\begin{" + env + "}[htbp]", "\\centering",
        f"\\caption{{{caption}}}", f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{{colspec}}}", "\\toprule", header, "\\midrule",
    ]
    out += body
    out += ["\\bottomrule", "\\end{tabular}"]
    if note:
        out.append(f"\\begin{{flushleft}}\\footnotesize {note}\\end{{flushleft}}")
    out += ["\\end{" + env + "}"]
    return out


# Metric-direction markers, assembled from chr(92): writing them as literals
# would put a backslash-u sequence in a non-raw string, which Python reads as
# the start of a Unicode escape.
_A = chr(92)
UP = '$' + _A + 'uparrow$'
DN = '$' + _A + 'downarrow$'


def _is_reference(model_key):
    """True for the reference-ceiling encoder, which is reported but never averaged."""
    return "SigLIP" in model_key


def tab_scale_study():
    rows, means = [], []
    for e in "ABC":
        j = load(f"zeroshot_eval_{e}.json")
        if not j:
            continue
        n = j["n_classes"]
        rows.append(f"\\multicolumn{{6}}{{l}}{{\\emph{{Config {e} --- {n} unseen classes, "
                    f"chance {pct(j['chance'])}}}}} \\\\")
        b_all, c_all, r_all, g_all = [], [], [], []
        for m, d in j["models"].items():
            b, c, r, g = (d["bare"]["acc"], d["crude"]["acc"],
                          d["rich"]["acc"], d["grounded"]["acc"])
            # The mean is over the four DEPLOYABLE encoders only. ViT-B-16-SigLIP2 is the
            # reference ceiling and the manuscript states throughout that it is excluded --
            # but this loop was averaging it in, so every printed mean was pulled toward the
            # ceiling and disagreed with the prose that quotes it.
            if not _is_reference(m):
                b_all.append(b); c_all.append(c)
                r_all.append(r); g_all.append(g)
            rows.append(f"\\quad {short(m)} & {d['bare']['img_params_M']:.1f} & {pct(b)} & "
                        f"{pct(d['crude']['acc'])} & {pct(r)} & {pct(g)} \\\\")
        mb, mc, mr, mg = (sum(x) / len(x) for x in (b_all, c_all, r_all, g_all))
        # The crude mean was printed as "---". That cell is the counterexample to "any full
        # symptom description beats a class name": crude LOSES to bare at B and C.
        rows.append(f"\\quad \\textbf{{mean}} & --- & \\textbf{{{pct(mb)}}} & "
                    f"\\textbf{{{pct(mc)}}} & \\textbf{{{pct(mr)}}} & "
                    f"\\textbf{{{pct(mg)}}} \\\\")
        rows.append("\\addlinespace")
        means.append((n, mb, mr, mg))
    if not rows:
        return
    note = ("\\emph{bare} = class name only; \\emph{rich} = hand-curated symptom paragraph; "
            "\\emph{grounded} = LLM source-grounded symptom text. Held-out crops are never trained "
            "on. Crop pools are nested (A $\\subset$ B $\\subset$ C), so differences are "
            "attributable to the size of the unseen label space. Note the reversal: mean "
            "hand-curated accuracy falls as classes grow while source-grounded accuracy rises.")
    write("tab_scale_study.tex", wrap(
        "Cross-crop zero-shot accuracy at three held-out scales, by descriptor strategy.",
        "tab:scale", "llrrrr",
        "Model & Params (M) & bare & crude & rich & grounded \\\\", rows, note, wide=True))


def tab_abstain():
    # Section 5.4 compares grounded against rich on top-5 and AURC, but this table printed only
    # the grounded rows, so no reader could check the claim. Both strategies now appear.
    body = []
    for e in "ABC":
        j = load(f"metrics_abstain_{e}.json")
        if not j:
            continue
        for m, d in j["models"].items():
            g, r = d.get("grounded"), d.get("rich")
            if not isinstance(g, dict):
                continue
            cells = [e, str(j["n_classes"]), short(m)]
            for sd in (g, r):
                if isinstance(sd, dict):
                    cells += [pct(sd.get("top1")), pct(sd.get("top5")), str(sd.get("aurc")),
                              pct(sd.get("acc@cov80"))]
                else:
                    cells += ["---"] * 4
            body.append(" & ".join(cells) + " " + (_A+_A))
    if not body:
        return
    write("tab_abstain.tex", wrap(
        "Top-5 and selective prediction, source-grounded against the hand-curated bank. "
        "acc@cov80 = accuracy when the 80\% most confident predictions are kept.",
        "tab:abstain", "lllrrrrrrrr",
        ("& & & " + _A + "multicolumn{4}{c}{grounded} & " + _A + "multicolumn{4}{c}{rich} "
         + (_A+_A) + chr(10) + _A + "cmidrule(lr){4-7}" + _A + "cmidrule(lr){8-11}" + chr(10)
         + "Config & Classes & Model & Top-1 & Top-5 & AURC $" + _A + "downarrow$ & acc@cov80 & "
         + "Top-1 & Top-5 & AURC $" + _A + "downarrow$ & acc@cov80 " + (_A+_A)),
        body,
        "Confidence is the top-1 minus top-2 similarity margin. Selective accuracy rising as "
        "coverage tightens confirms the signal is correctly ordered; the gate itself buys about "
        "two points of top-1 for refusing one image in five.", wide=True))


def tab_seen():
    probes = {e: load(f"probe_seen_{e}.json") for e in "ABC"}
    probes = {e: p for e, p in probes.items() if p}
    if not probes:
        return
    cols = sorted({m for p in probes.values() for m in p["models"]},
                  key=lambda m: next(p["models"][m]["img_params_M"]
                                     for p in probes.values() if m in p["models"]))
    body = []
    for e, p in probes.items():
        n_img = p.get("seen_images")
        accs = " & ".join(pct(p["models"].get(c, {}).get("seen_probe_top1")) for c in cols)
        body.append(f"{e} & {p.get('n_seen_crops', len(p['seen_crops']))} & {p['seen_classes']} & "
                    f"{'---' if n_img is None else f'{n_img:,}'} & {accs} \\\\")
    header = ("Config & Crops & Classes & Images & "
              + " & ".join(short(c) for c in cols) + " \\\\")
    write("tab_seen.tex", wrap(
        "Known-crop accuracy: frozen backbone plus a linear probe, at three seen-set sizes.",
        "tab:seen", "lrrr" + "r" * len(cols), header, body,
        "The same frozen encoders that perform unseen-crop zero-shot (Table~\\ref{tab:scale}). "
        "Accuracy rises with the seen label space because additional crops contribute "
        "proportionally more training images than difficulty.", wide=True))


def tab_supervised():
    # Params are printed because Section 5.5 argues "capacity is not the lever" from this table.
    # Without the column a reader cannot check that claim against the numbers shown.
    rows = []
    for f in sorted(HERE.glob("supervised_*.json")):
        d = json.loads(f.read_text(encoding="utf-8"))
        rows.append((d.get("arch"), d.get("params_M"), d.get("seen_classes"), d.get("seen_top1")))
    if not rows:
        return
    body = [f"{a.replace('_', '-')} & {p:.1f} & {n} & {pct(t)} & \\textbf{{n/a (structural)}} \\\\"
            for a, p, n, t in sorted(rows, key=lambda r: -(r[3] or 0))]
    # The caption used to assert "a 4.4 M network finishes within 0.1 points of the best of the
    # fourteen" no matter how many architectures were actually present, so a partial sweep
    # printed a claim about results the table did not contain. Derive it from the rows instead,
    # and say plainly when the sweep is incomplete.
    _n = len(rows)
    _best = max(rows, key=lambda r: r[3] or 0)
    _small = min(rows, key=lambda r: r[1] or 9e9)
    _gap = (_best[3] or 0) - (_small[3] or 0)
    _cap = ("Supervised CNN baselines on the identical seen set."
            if _n >= 14 else
            f"Supervised CNN baselines on the identical seen set "
            f"({_n} of 14 architectures; the remainder had not completed at build time).")
    # State the comparison that actually carries the claim. "The smallest finishes within
    # 9.2 points of the best" is true but argues the WRONG way -- 9.2 points is a wide gap.
    # What supports "size is not the bottleneck" is that the BEST network is one of the
    # smallest: efficientnet_b0 at 4.2 M beats resnet101 at 42.8 M by 2.5 points. Both halves
    # are computed and the sentence is emitted only when the data support it.
    _largest = max(rows, key=lambda r: r[1] or 0)
    _obs = ""
    if _n >= 14 and (_best[3] or 0) > (_largest[3] or 0):
        _ratio = (_largest[1] or 0) / max(_best[1] or 1e-9, 1e-9)
        _lead = ((_best[3] or 0) - (_largest[3] or 0)) * 100
        _obs = ("Accuracy does not track parameter count: the strongest network is "
                + _best[0].replace("_", "-") + " at %.1f\,M, " % _best[1]
                + "which is %.0f$\\times$ smaller than the largest model here and beats " % _ratio
                + "it by %.1f points. " % _lead)
    write("tab_supervised.tex", wrap(
        _cap,
        "tab:cnn", "lrrrr",
        "Architecture & Params (M) & Classes & Seen top-1 " + UP + " & Unseen \\\\", body,
        "For a fixed, known label set a CNN is the stronger classifier. " + _obs +
        "None of them, however, has "
        "an output unit for an unseen class, so cross-crop accuracy is not low but undefined --- "
        "the capability the descriptor head supplies.", wide=True))


def tab_wiseft():
    # Prefer the re-measured file. scripts/wiseft.py writes wiseft.json and measures BOTH
    # sides under one protocol; the legacy run_all file recorded unseen_classes=17 (the pilot)
    # against seen_classes=166 (nested C), i.e. one table reporting two different experiments.
    # Falling back to the legacy file keeps the table renderable before the re-run lands, but
    # the caption then carries its protocol so the mixture is visible rather than hidden.
    j = load("wiseft.json") or load("run_all_exp3_lw11_full.json")
    if not j:
        return
    _legacy = "protocol" not in j
    _proto = j.get("protocol", "pilot unseen set with nested-C seen set -- MIXED PROTOCOLS")
    sweep = j["sweep"]

    # A sweep carrying warnings failed its own sanity gates, and the 2026-09-06 run showed
    # what that looks like: seen ran 58.7 -> 45.1 -> 63.8, a midpoint below both endpoints,
    # so the weights were not linearly connected and no row of the table meant anything.
    # Say so in the caption rather than printing the numbers as if they were usable.
    _warn = j.get("warnings") or []

    # The footnote used to assert that alpha=0.5 is the deployable setting no matter what the
    # sweep showed -- the one claim the broken run most conspicuously refuted. Derive the
    # recommendation from the data: the alpha maximising seen+unseen, which is what
    # scripts/wiseft.py records as `best`.
    _best = j.get("best") or max(sweep, key=lambda r: r["seen"] + r["unseen"])
    _mono = all(sweep[i]["seen"] <= sweep[i + 1]["seen"] + 1e-9 for i in range(len(sweep) - 1))

    lab = {0.0: "0.0 (frozen)", 1.0: "1.0 (naive fine-tune)"}
    body = []
    for r in sweep:
        name = lab.get(r["alpha"], "%.2f" % r["alpha"])
        body.append(name + " & " + pct(r["seen"]) + " & " + pct(r["unseen"]) + r" \\")

    _cap = (f"WiSE-FT weight ensembling on {j['model']}: the seen/unseen trade-off as a single "
            f"dial ({j['seen_classes']} seen classes, {j['seen_images']:,} images; "
            f"{j.get('unseen_classes', '?')} unseen classes; protocol: {_proto}).")
    if _legacy:
        _cap += " NOTE: legacy file, protocols differ between the two columns."
    if _warn:
        _cap += (" NOTE: this sweep did not pass its own consistency checks and is reported "
                 "for completeness only.")

    # Whether alpha=1 forgets is a question for the data, not a fixed sentence. The
    # 2026-09-06 sweep collapsed to 1.8% unseen against a 1.96% chance floor -- forgetting.
    # The 2026-09-07 sweep holds 16.4%, over eight times chance, while gaining 22.5 points on
    # seen: that is not catastrophic forgetting and the caption must not say it is.
    _a1 = next((r for r in sweep if r["alpha"] == 1.0), None)
    _chance = j.get("unseen_chance") or (1.0 / max(j.get("unseen_classes") or 1, 1))
    # "reproduces the frozen baseline" invited the reader to compare against Table 3's
    # 82.2%, which is a different measurement: this sweep subsamples the seen split to
    # 200 images per class, so its frozen reference is ~59%. Say which baseline.
    _foot = ("$\\alpha=0$ reproduces this sweep's own frozen probe "
             f"({j.get('frozen_probe', 0) * 100:.1f}\\%), validating the interpolation. "
             "That probe is measured on the 200-image-per-class subsample used here, not on "
             "the full seen split of Table~\\ref{tab:seen}. ")
    if _a1:
        _mult = _a1["unseen"] / _chance if _chance else 0.0
        if _mult < 2.0:
            _foot += ("$\\alpha=1$ is naive fine-tuning and shows catastrophic forgetting, "
                      f"retaining only {_mult:.1f}$\\times$ chance on unseen crops. ")
        else:
            _foot += (f"$\\alpha=1$ is naive fine-tuning; here it still retains "
                      f"{_mult:.1f}$\\times$ chance on unseen crops, so the dial trades "
                      "cross-crop transfer for seen accuracy rather than destroying it. ")
    if _warn:
        # Trim on a word boundary: a mid-word cut reads as a typesetting error rather than
        # as a deliberately abbreviated warning.
        _w = _warn[0].split(" -- ")[0].rstrip(" .")
        _foot += ("The intermediate points are not interpretable here: " + _w + ". ")
    elif _mono:
        _foot += (f"Seen accuracy rises monotonically with $\\alpha$ while unseen accuracy "
                  f"falls, so the dial trades one for the other as intended; "
                  f"$\\alpha={_best['alpha']:.2f}$ maximises their sum.")
    else:
        _foot += (f"$\\alpha={_best['alpha']:.2f}$ maximises the sum of the two columns.")

    write("tab_wiseft.tex", wrap(
        _cap, "tab:wiseft", "lrr",
        "$\\alpha$ & Seen " + UP + " & Unseen zero-shot " + UP + " \\\\", body, _foot))


def tab_edge():
    j = load("edge_quant_benchmark.json")
    if not j:
        return
    body = []
    for _k, d in j["models"].items():
        v = d.get("variants", {})
        g = lambda n, f="p50_ms": v.get(n, {}).get(f)
        fm = lambda x: "---" if x is None else f"{x:.1f}"
        body.append(f"{short(d['model'])} & {d['img_params_M']:.1f} & {fm(g('torch_fp32'))} & "
                    f"{fm(g('onnx_fp32'))} & {fm(g('onnx_int8_dynamic'))} & "
                    f"{fm(g('onnx_int8_static'))} & {g('onnx_fp32', 'size_mb')} & "
                    f"{g('onnx_int8_static', 'size_mb')} \\\\")
    write("tab_edge.tex", wrap(
        "On-device cost of the deployable image encoder (CPU, batch 1, $224\\times224$). "
        "The four latency columns are milliseconds; the final two are megabytes.",
        "tab:edge", "lrrrrrrr",
        "Model & Params (M) & Torch FP32 " + DN + " & ONNX FP32 " + DN + " & "
        "INT8 dyn. " + DN + " & INT8 static " + DN + " & FP32 " + DN + " & "
        "INT8 " + DN + " \\\\", body,
        f"Latency in ms (median of {j['runs']} runs), ONNX Runtime {j.get('ort_version')}. "
        "INT8 makes the hybrid conv--transformer tiers \\emph{slower} while shrinking them "
        "$\\sim3.5\\times$; only the pure-transformer model gets faster.", wide=True))


def tab_loco():
    j = load("loco_s0_rich.json")
    if not j:
        return
    body = []
    for crop, d in sorted(j["per_crop"].items(), key=lambda kv: -kv[1]["acc"]):
        ci = d.get("ci95", [None, None])
        body.append(f"{crop} & {d['n']:,} & {pct(d['acc'])} & [{pct(ci[0])}, {pct(ci[1])}] \\\\")
    p = j["pooled"]
    body.append("\\midrule")
    body.append(f"\\textbf{{Pooled}} & \\textbf{{{p['n']:,}}} & \\textbf{{{pct(p['acc'])}}} & "
                f"[{pct(p['ci95'][0])}, {pct(p['ci95'][1])}] \\\\")
    write("tab_loco.tex", wrap(
        f"Leave-one-crop-out on {j['model']} ({j['n_classes']} classes, chance {pct(j['chance'])}).",
        "tab:loco", "lrrl",
        "Crop & $N$ & Zero-shot " + UP + " & 95\\% CI \\\\", body,
        "The two hardest crops are both \\emph{trained} crops, so difficulty does not "
        "follow the held-out boundary. The held-out crops nevertheless average above the "
        "trained pool here (19.0\\% against 9.0\\%), so this split is not "
        "adversarially hard. Measured with the \\texttt{rich} strategy on the "
        "78-class leave-one-crop-out pool, not the headline label space."))


if __name__ == "__main__":
    for fn in (tab_scale_study, tab_abstain, tab_seen, tab_supervised,
               tab_wiseft, tab_edge, tab_loco):
        try:
            fn()
        except Exception as e:
            print(f"[tex] FAILED {fn.__name__}: {type(e).__name__}: {e}")
