"""
Emit Elsevier-ready LaTeX tables (booktabs) from the SAME result JSONs make_tables.py reads.

WHY: the manuscript is tex/main.tex and its tables are generated. Maintaining tables in
both by hand is how the paper drifted from the data three times. main.tex \\input{}s these files, so
there is exactly one source of truth -- the JSONs -- for every number in either format.

    python docs/paper/make_tex_tables.py      # writes docs/paper/tex/tab_*.tex
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = Path(__file__).resolve().parent
TEX = HERE / "tex"
TEX.mkdir(parents=True, exist_ok=True)


def load(name):
    p = HERE / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def pct(x, nd=1):
    return "---" if x is None else f"{x * 100:.{nd}f}\\%"


def short(n):
    return n.split("/")[0].replace("_", "-")


def write(fname, lines):
    (TEX / fname).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[tex] wrote {TEX / fname}")


def wrap(caption, label, colspec, header, body, note=None):
    out = [
        "% GENERATED by docs/paper/make_tex_tables.py -- do not edit by hand.",
        "\\begin{table}[htbp]", "\\centering",
        f"\\caption{{{caption}}}", f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{{colspec}}}", "\\toprule", header, "\\midrule",
    ]
    out += body
    out += ["\\bottomrule", "\\end{tabular}"]
    if note:
        out.append(f"\\begin{{flushleft}}\\footnotesize {note}\\end{{flushleft}}")
    out += ["\\end{table}"]
    return out


def _is_reference(model_key):
    """True for the reference-ceiling encoder, which is reported but never averaged."""
    return "SigLIP" in model_key


def tab_scale_study():
    rows, means = [], []
    for e in "ABC":
        j = load(f"zeroshot_eval_{e}.json")
        if not j:
            continue
        n = j["n_classes"]
        rows.append(f"\\multicolumn{{6}}{{l}}{{\\emph{{Config {e} --- {n} unseen classes, "
                    f"chance {pct(j['chance'])}}}}} \\\\")
        b_all, r_all, g_all = [], [], []
        for m, d in j["models"].items():
            b, r, g = d["bare"]["acc"], d["rich"]["acc"], d["grounded"]["acc"]
            # The mean is over the four DEPLOYABLE encoders only. ViT-B-16-SigLIP2 is the
            # reference ceiling and the manuscript states throughout that it is excluded --
            # but this loop was averaging it in, so every printed mean was pulled toward the
            # ceiling and disagreed with the prose that quotes it.
            if not _is_reference(m):
                b_all.append(b); r_all.append(r); g_all.append(g)
            rows.append(f"\\quad {short(m)} & {d['bare']['img_params_M']:.1f} & {pct(b)} & "
                        f"{pct(d['crude']['acc'])} & {pct(r)} & {pct(g)} \\\\")
        mb, mr, mg = (sum(x) / len(x) for x in (b_all, r_all, g_all))
        rows.append(f"\\quad \\textbf{{mean}} & --- & \\textbf{{{pct(mb)}}} & --- & "
                    f"\\textbf{{{pct(mr)}}} & \\textbf{{{pct(mg)}}} \\\\")
        rows.append("\\addlinespace")
        means.append((n, mb, mr, mg))
    if not rows:
        return
    note = ("\\emph{bare} = class name only; \\emph{rich} = hand-curated symptom paragraph; "
            "\\emph{grounded} = LLM source-grounded symptom text. Held-out crops are never trained "
            "on. Crop pools are nested (A $\\subset$ B $\\subset$ C), so differences are "
            "attributable to the size of the unseen label space. Note the reversal: mean "
            "hand-curated accuracy falls as classes grow while source-grounded accuracy rises.")
    write("tab_scale_study.tex", wrap(
        "Cross-crop zero-shot accuracy at three held-out scales, by descriptor strategy.",
        "tab:scale", "llrrrr",
        "Model & Params (M) & bare & crude & rich & grounded \\\\", rows, note))


def tab_abstain():
    body = []
    for e in "ABC":
        j = load(f"metrics_abstain_{e}.json")
        if not j:
            continue
        for m, d in j["models"].items():
            sd = d.get("grounded")
            if not isinstance(sd, dict):
                continue
            body.append(f"{e} & {j['n_classes']} & {short(m)} & {pct(sd.get('top1'))} & "
                        f"{pct(sd.get('top5'))} & {sd.get('aurc')} & "
                        f"{pct(sd.get('acc@cov90'))} & {pct(sd.get('acc@cov80'))} \\\\")
    if not body:
        return
    write("tab_abstain.tex", wrap(
        "Top-5 and selective prediction with source-grounded descriptors. "
        "acc@cov$X$ = accuracy when the $X\\%$ most confident predictions are kept.",
        "tab:abstain", "llrrrrrr",
        "Config & Classes & Model & Top-1 & Top-5 & AURC $\\downarrow$ & acc@cov90 & acc@cov80 \\\\",
        body,
        "Confidence is the top-1 minus top-2 similarity margin. Selective accuracy rising as "
        "coverage tightens confirms the confidence signal is correctly ordered."))


def tab_seen():
    probes = {e: load(f"probe_seen_{e}.json") for e in "ABC"}
    probes = {e: p for e, p in probes.items() if p}
    if not probes:
        return
    cols = sorted({m for p in probes.values() for m in p["models"]},
                  key=lambda m: next(p["models"][m]["img_params_M"]
                                     for p in probes.values() if m in p["models"]))
    body = []
    for e, p in probes.items():
        n_img = p.get("seen_images")
        accs = " & ".join(pct(p["models"].get(c, {}).get("seen_probe_top1")) for c in cols)
        body.append(f"{e} & {p.get('n_seen_crops', len(p['seen_crops']))} & {p['seen_classes']} & "
                    f"{'---' if n_img is None else f'{n_img:,}'} & {accs} \\\\")
    header = ("Config & Crops & Classes & Images & "
              + " & ".join(short(c) for c in cols) + " \\\\")
    write("tab_seen.tex", wrap(
        "Known-crop accuracy: frozen backbone plus a linear probe, at three seen-set sizes.",
        "tab:seen", "lrrr" + "r" * len(cols), header, body,
        "The same frozen encoders that perform unseen-crop zero-shot (Table~\\ref{tab:scale}). "
        "Accuracy rises with the seen label space because additional crops contribute "
        "proportionally more training images than difficulty."))


def tab_supervised():
    # Params are printed because Section 5.5 argues "capacity is not the lever" from this table.
    # Without the column a reader cannot check that claim against the numbers shown.
    rows = []
    for f in sorted(HERE.glob("supervised_*.json")):
        d = json.loads(f.read_text(encoding="utf-8"))
        rows.append((d.get("arch"), d.get("params_M"), d.get("seen_classes"), d.get("seen_top1")))
    if not rows:
        return
    body = [f"{a.replace('_', '-')} & {p:.1f} & {n} & {pct(t)} & \\textbf{{0 (structural)}} \\\\"
            for a, p, n, t in sorted(rows, key=lambda r: -(r[3] or 0))]
    write("tab_supervised.tex", wrap(
        "Supervised CNN baselines on the identical seen set.",
        "tab:cnn", "lrrrr",
        "Architecture & Params (M) & Classes & Seen top-1 & Unseen \\\\", body,
        "For a fixed, known label set a CNN is the stronger classifier. Accuracy does not track "
        "parameter count: a 4.4\,M network finishes within 0.1 points of the best of the "
        "fourteen, and the largest model is not the best. None of them, however, has "
        "an output unit for an unseen class, so cross-crop accuracy is not low but undefined --- "
        "the capability the descriptor head supplies."))


def tab_wiseft():
    j = load("run_all_exp3_lw11_full.json")
    if not j:
        return
    lab = {0.0: "0.0 (frozen)", 0.5: "0.5 (WiSE-FT)", 1.0: "1.0 (naive fine-tune)"}
    body = [f"{lab.get(s['alpha'], s['alpha'])} & {pct(s['seen'])} & {pct(s['unseen'])} \\\\"
            for s in j["sweep"]]
    write("tab_wiseft.tex", wrap(
        f"WiSE-FT weight ensembling on {j['model']}: the seen/unseen trade-off as a single dial "
        f"({j['seen_classes']} seen classes, {j['seen_images']:,} images).",
        "tab:wiseft", "lrr",
        "$\\alpha$ & Seen & Unseen (zero-shot) \\\\", body,
        "$\\alpha=0$ reproduces the frozen baseline exactly, validating the interpolation. "
        "$\\alpha=1$ is catastrophic forgetting. $\\alpha=0.5$ is the deployable setting."))


def tab_edge():
    j = load("edge_quant_benchmark.json")
    if not j:
        return
    body = []
    for _k, d in j["models"].items():
        v = d.get("variants", {})
        g = lambda n, f="p50_ms": v.get(n, {}).get(f)
        fm = lambda x: "---" if x is None else f"{x:.1f}"
        body.append(f"{short(d['model'])} & {d['img_params_M']:.1f} & {fm(g('torch_fp32'))} & "
                    f"{fm(g('onnx_fp32'))} & {fm(g('onnx_int8_dynamic'))} & "
                    f"{fm(g('onnx_int8_static'))} & {g('onnx_fp32', 'size_mb')} & "
                    f"{g('onnx_int8_static', 'size_mb')} \\\\")
    write("tab_edge.tex", wrap(
        "On-device cost of the deployable image encoder (CPU, batch 1, $224\\times224$).",
        "tab:edge", "lrrrrrrr",
        "Model & Params (M) & Torch FP32 & ONNX FP32 & INT8 dyn. & INT8 static & FP32 (MB) & "
        "INT8 (MB) \\\\", body,
        f"Latency in ms (median of {j['runs']} runs), ONNX Runtime {j.get('ort_version')}. "
        "INT8 makes the hybrid conv--transformer tiers \\emph{slower} while shrinking them "
        "$\\sim3.5\\times$; only the pure-transformer model gets faster."))


def tab_loco():
    j = load("loco_s0_rich.json")
    if not j:
        return
    body = []
    for crop, d in sorted(j["per_crop"].items(), key=lambda kv: -kv[1]["acc"]):
        ci = d.get("ci95", [None, None])
        body.append(f"{crop} & {d['n']:,} & {pct(d['acc'])} & [{pct(ci[0])}, {pct(ci[1])}] \\\\")
    p = j["pooled"]
    body.append("\\midrule")
    body.append(f"\\textbf{{Pooled}} & \\textbf{{{p['n']:,}}} & \\textbf{{{pct(p['acc'])}}} & "
                f"[{pct(p['ci95'][0])}, {pct(p['ci95'][1])}] \\\\")
    write("tab_loco.tex", wrap(
        f"Leave-one-crop-out on {j['model']} ({j['n_classes']} classes, chance {pct(j['chance'])}).",
        "tab:loco", "lrrl",
        "Crop & $N$ & Zero-shot & 95\\% CI \\\\", body,
        "Held-out crops fall in the middle of the range and two \\emph{trained} crops are the "
        "hardest, so the headline held-out set is not a favourable split."))


if __name__ == "__main__":
    for fn in (tab_scale_study, tab_abstain, tab_seen, tab_supervised,
               tab_wiseft, tab_edge, tab_loco):
        try:
            fn()
        except Exception as e:
            print(f"[tex] FAILED {fn.__name__}: {type(e).__name__}: {e}")
