"""
Emit Elsevier-ready LaTeX tables (booktabs) from the SAME result JSONs make_tables.py reads.

WHY: the manuscript is tex/main.tex and its tables are generated. Maintaining tables in
both by hand is how the paper drifted from the data three times. main.tex \\input{}s these files, so
there is exactly one source of truth -- the JSONs -- for every number in either format.

    python docs/paper/make_tex_tables.py      # writes docs/paper/tex/tab_*.tex
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = Path(__file__).resolve().parent
TEX = HERE / "tex"
TEX.mkdir(parents=True, exist_ok=True)


def load(name):
    p = HERE / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def pct(x, nd=1):
    return "---" if x is None else f"{x * 100:.{nd}f}\\%"


def short(n):
    return n.split("/")[0].replace("_", "-")


def write(fname, lines):
    # newline="" prevents Windows CRLF translation. write_text() was silently emitting
    # CRLF into every generated table; main.tex is LF-only, so the two halves of the
    # manuscript had different line endings and only main.tex was ever checked.
    with open(TEX / fname, "w", encoding="utf-8", newline="") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"[tex] wrote {TEX / fname}")


def wrap(caption, label, colspec, header, body, note=None, wide=False):
    """Render one booktabs table. `wide` promotes it to table*, spanning both
    columns: an eight-column numeric table does not fit the cas-dc single-column
    measure once its headers carry units and direction markers."""
    env = "table*" if wide else "table"
    out = [
        "% GENERATED by docs/paper/make_tex_tables.py -- do not edit by hand.",
        "\\begin{" + env + "}[htbp]", "\\centering",
        f"\\caption{{{caption}}}", f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{{colspec}}}", "\\toprule", header, "\\midrule",
    ]
    out += body
    out += ["\\bottomrule", "\\end{tabular}"]
    if note:
        out.append(f"\\begin{{flushleft}}\\footnotesize {note}\\end{{flushleft}}")
    out += ["\\end{" + env + "}"]
    return out


# Metric-direction markers, assembled from chr(92): writing them as literals
# would put a backslash-u sequence in a non-raw string, which Python reads as
# the start of a Unicode escape.
_A = chr(92)
UP = '$' + _A + 'uparrow$'
DN = '$' + _A + 'downarrow$'


def _is_reference(model_key):
    """True for the reference-ceiling encoder, which is reported but never averaged."""
    return "SigLIP" in model_key


def tab_scale_study():
    rows, means = [], []
    for e in "ABC":
        j = load(f"zeroshot_eval_{e}.json")
        if not j:
            continue
        n = j["n_classes"]
        rows.append(f"\\multicolumn{{6}}{{l}}{{\\emph{{Config {e} --- {n} unseen classes, "
                    f"chance {pct(j['chance'])}}}}} \\\\")
        b_all, c_all, r_all, g_all = [], [], [], []
        for m, d in j["models"].items():
            b, c, r, g = (d["bare"]["acc"], d["crude"]["acc"],
                          d["rich"]["acc"], d["grounded"]["acc"])
            # The mean is over the four DEPLOYABLE encoders only. ViT-B-16-SigLIP2 is the
            # reference ceiling and the manuscript states throughout that it is excluded --
            # but this loop was averaging it in, so every printed mean was pulled toward the
            # ceiling and disagreed with the prose that quotes it.
            if not _is_reference(m):
                b_all.append(b); c_all.append(c)
                r_all.append(r); g_all.append(g)
            rows.append(f"\\quad {short(m)} & {d['bare']['img_params_M']:.1f} & {pct(b)} & "
                        f"{pct(d['crude']['acc'])} & {pct(r)} & {pct(g)} \\\\")
        mb, mc, mr, mg = (sum(x) / len(x) for x in (b_all, c_all, r_all, g_all))
        # The crude mean was printed as "---". That cell is the counterexample to "any full
        # symptom description beats a class name": crude LOSES to bare at B and C.
        rows.append(f"\\quad \\textbf{{mean}} & --- & \\textbf{{{pct(mb)}}} & "
                    f"\\textbf{{{pct(mc)}}} & \\textbf{{{pct(mr)}}} & "
                    f"\\textbf{{{pct(mg)}}} \\\\")
        rows.append("\\addlinespace")
        means.append((n, mb, mr, mg))
    if not rows:
        return
    # CAPTION REWRITTEN. The previous note read "Note the reversal: mean hand-curated accuracy
    # falls as classes grow while source-grounded accuracy rises", which asserts exactly the
    # claim Section 7 withdraws after the de-duplicated re-run. A caption is what a skimming
    # reader takes away, so it must not carry a retracted claim. It also has to say that the
    # bank is a collision-limited reference (Section 3.4) and that each cell is one registry.
    note = ("\\emph{bare} = class name only; \\emph{rich} = hand-curated symptom paragraph; "
            "\\emph{grounded} = LLM source-grounded symptom text. Held-out crops are never trained "
            "on. Crop pools are nested (A $\\subset$ B $\\subset$ C), but each step also adds new "
            "crops, so the columns are not a controlled measurement of label-space size alone "
            "(Section~\\ref{sec:data}). The mean row is over the four deployable tiers; the "
            "92.9\\,M reference encoder is excluded. The keyword bank's mean falls as the label "
            "space grows while source-grounded text holds; the bank's prototypes collide "
            "(Section~\\ref{sec:strategies}), so that gap measures per-class distinctness rather "
            "than grounding. Every cell is a single descriptor registry scored once, against a "
            "generation-to-generation standard deviation of 2.4 points (Section~\\ref{sec:desc}).")
    write("tab_scale_study.tex", wrap(
        "Cross-crop zero-shot accuracy at three held-out scales, by descriptor strategy.",
        "tab:scale", "llrrrr",
        "Model & Params (M) & bare & crude & rich & grounded \\\\", rows, note, wide=True))


def tab_abstain():
    # Section 5.4 compares grounded against rich on top-5 and AURC, but this table printed only
    # the grounded rows, so no reader could check the claim. Both strategies now appear.
    #
    # TOP-1 IS READ FROM zeroshot_eval_*.json, NOT FROM metrics_abstain_*.json, even though both
    # files carry it. metrics_abstain stores accuracies already rounded to four decimals, so
    # MobileCLIP-B/rich at configuration B is 0.2835 there against 0.2835393889853888 in
    # zeroshot_eval_B.json. Formatted to one decimal those differ -- 28.3% vs 28.4% -- and this
    # table printed 28.3 while tab_scale_study printed 28.4 for the same cell. One quantity, one
    # source: the full-precision file wins, and any future top-1 column must read from it too.
    body = []
    for e in "ABC":
        j = load(f"metrics_abstain_{e}.json")
        if not j:
            continue
        zs = (load(f"zeroshot_eval_{e}.json") or {}).get("models", {})
        for m, d in j["models"].items():
            g, r = d.get("grounded"), d.get("rich")
            if not isinstance(g, dict):
                continue
            cells = [e, str(j["n_classes"]), short(m)]
            for name, sd in (("grounded", g), ("rich", r)):
                if isinstance(sd, dict):
                    top1 = zs.get(m, {}).get(name, {}).get("acc", sd.get("top1"))
                    # AURC is stored at 4 dp; str() dropped trailing zeros (0.584 beside 0.6986)
                    aurc = sd.get("aurc")
                    cells += [pct(top1), pct(sd.get("top5")),
                              "---" if aurc is None else f"{aurc:.4f}",
                              pct(sd.get("acc@cov80"))]
                else:
                    cells += ["---"] * 4
            body.append(" & ".join(cells) + " " + (_A+_A))
    if not body:
        return
    write("tab_abstain.tex", wrap(
        "Top-5 and selective prediction, source-grounded against the hand-curated bank. "
        "acc@cov80 = accuracy when the 80\% most confident predictions are kept; "
        "AURC = area under the risk--coverage curve, lower is better.",
        "tab:abstain", "lllrrrrrrrr",
        ("& & & " + _A + "multicolumn{4}{c}{grounded} & " + _A + "multicolumn{4}{c}{rich} "
         + (_A+_A) + chr(10) + _A + "cmidrule(lr){4-7}" + _A + "cmidrule(lr){8-11}" + chr(10)
         + "Config & Classes & Model & Top-1 & Top-5 & AURC $" + _A + "downarrow$ & acc@cov80 & "
         + "Top-1 & Top-5 & AURC $" + _A + "downarrow$ & acc@cov80 " + (_A+_A)),
        body,
        "Confidence is the top-1 minus top-2 similarity margin. Selective accuracy rises at every "
        "step of the reported coverage grid (100\% down to 50\% in tens) in all 30 cells, "
        "confirming the signal is correctly ordered; the gate itself buys about "
        "two points of top-1 for refusing one image in five.", wide=True))


def tab_seen():
    probes = {e: load(f"probe_seen_{e}.json") for e in "ABC"}
    probes = {e: p for e, p in probes.items() if p}
    if not probes:
        return
    cols = sorted({m for p in probes.values() for m in p["models"]},
                  key=lambda m: next(p["models"][m]["img_params_M"]
                                     for p in probes.values() if m in p["models"]))
    body = []
    for e, p in probes.items():
        n_img = p.get("seen_images")
        accs = " & ".join(pct(p["models"].get(c, {}).get("seen_probe_top1")) for c in cols)
        body.append(f"{e} & {p.get('n_seen_crops', len(p['seen_crops']))} & {p['seen_classes']} & "
                    f"{'---' if n_img is None else f'{n_img:,}'} & {accs} \\\\")
    header = ("Config & Crops & Classes & Images & "
              + " & ".join(short(c) for c in cols) + " \\\\")
    write("tab_seen.tex", wrap(
        "Known-crop accuracy: frozen backbone plus a linear probe, at three seen-set sizes.",
        "tab:seen", "lrrr" + "r" * len(cols), header, body,
        # MECHANISM REMOVED. The "because" clause was falsified by this table's own columns:
        # images grow 1.65x from A to C while classes grow 1.71x, so images per class FALL
        # (436 -> 403 -> 421). Report the trend; do not assert a cause the numbers contradict.
        "The same frozen encoders that perform unseen-crop zero-shot (Table~\\ref{tab:scale}). "
        "Accuracy rises with the seen label space; note that images per class do not rise with "
        "it (436, 403 and 421 at A, B and C), so the trend is not explained by the added crops "
        "bringing proportionally more training data.", wide=True))


def tab_supervised():
    # Params are printed because Section 5.5 argues "capacity is not the lever" from this table.
    # Without the column a reader cannot check that claim against the numbers shown.
    rows = []
    for f in sorted(HERE.glob("supervised_*.json")):
        d = json.loads(f.read_text(encoding="utf-8"))
        rows.append((d.get("arch"), d.get("params_M"), d.get("seen_classes"), d.get("seen_top1")))
    if not rows:
        return
    body = [f"{a.replace('_', '-')} & {p:.1f} & {n} & {pct(t)} & \\textbf{{n/a (structural)}} \\\\"
            for a, p, n, t in sorted(rows, key=lambda r: -(r[3] or 0))]
    # The caption used to assert "a 4.4 M network finishes within 0.1 points of the best of the
    # fourteen" no matter how many architectures were actually present, so a partial sweep
    # printed a claim about results the table did not contain. Derive it from the rows instead,
    # and say plainly when the sweep is incomplete.
    _n = len(rows)
    _best = max(rows, key=lambda r: r[3] or 0)
    _small = min(rows, key=lambda r: r[1] or 9e9)
    _gap = (_best[3] or 0) - (_small[3] or 0)
    _cap = ("Supervised CNN baselines on the identical seen set."
            if _n >= 14 else
            f"Supervised CNN baselines on the identical seen set "
            f"({_n} of 14 architectures; the remainder had not completed at build time).")
    # State the comparison that actually carries the claim. "The smallest finishes within
    # 9.2 points of the best" is true but argues the WRONG way -- 9.2 points is a wide gap.
    # What supports "size is not the bottleneck" is that the BEST network is one of the
    # smallest: efficientnet_b0 at 4.2 M beats resnet101 at 42.8 M by 2.5 points. Both halves
    # are computed and the sentence is emitted only when the data support it.
    _largest = max(rows, key=lambda r: r[1] or 0)
    _obs = ""
    if _n >= 14 and (_best[3] or 0) > (_largest[3] or 0):
        _ratio = (_largest[1] or 0) / max(_best[1] or 1e-9, 1e-9)
        _lead = ((_best[3] or 0) - (_largest[3] or 0)) * 100
        _obs = ("Accuracy tracks parameter count weakly at best: the strongest network is "
                + _best[0].replace("_", "-") + " at %.1f\,M, " % _best[1]
                + "which is %.0f$\\times$ smaller than the largest model here and beats " % _ratio
                + "it by %.1f points " % _lead
                # _lead is unrounded (89.27 - 86.73 = 2.54 -> 2.5), so subtracting the two
                # rounded cells above gives 2.6 and reads as an arithmetic slip. Show the
                # operands to two decimals so the difference reconciles on the page.
                + "(%.2f\\%% against %.2f\\%%). " % ((_best[3] or 0) * 100, (_largest[3] or 0) * 100))
    write("tab_supervised.tex", wrap(
        _cap,
        "tab:cnn", "lrrrr",
        "Architecture & Params (M) & Classes & Seen top-1 " + UP + " & Unseen \\\\", body,
        "For a fixed, known label set a CNN is the stronger classifier. " + _obs +
        "None of them, however, has "
        "an output unit for an unseen class, so cross-crop accuracy is not low but undefined --- "
        "the capability the descriptor head supplies.", wide=True))


def tab_wiseft():
    # Prefer the re-measured file. scripts/wiseft.py writes wiseft.json and measures BOTH
    # sides under one protocol; the legacy run_all file recorded unseen_classes=17 (the pilot)
    # against seen_classes=166 (nested C), i.e. one table reporting two different experiments.
    # Falling back to the legacy file keeps the table renderable before the re-run lands, but
    # the caption then carries its protocol so the mixture is visible rather than hidden.
    j = load("wiseft.json") or load("run_all_exp3_lw11_full.json")
    if not j:
        return
    _legacy = "protocol" not in j
    _proto = j.get("protocol", "pilot unseen set with nested-C seen set -- MIXED PROTOCOLS")
    sweep = j["sweep"]

    # A sweep carrying warnings failed its own sanity gates, and the 2026-09-06 run showed
    # what that looks like: seen ran 58.7 -> 45.1 -> 63.8, a midpoint below both endpoints,
    # so the weights were not linearly connected and no row of the table meant anything.
    # Say so in the caption rather than printing the numbers as if they were usable.
    _warn = j.get("warnings") or []

    # The footnote used to assert that alpha=0.5 is the deployable setting no matter what the
    # sweep showed -- the one claim the broken run most conspicuously refuted. Derive the
    # recommendation from the data: the alpha maximising seen+unseen, which is what
    # scripts/wiseft.py records as `best`.
    _best = j.get("best") or max(sweep, key=lambda r: r["seen"] + r["unseen"])
    _mono = all(sweep[i]["seen"] <= sweep[i + 1]["seen"] + 1e-9 for i in range(len(sweep) - 1))

    lab = {0.0: "0.0 (frozen)", 1.0: "1.0 (naive fine-tune)"}
    body = []
    for r in sweep:
        name = lab.get(r["alpha"], "%.2f" % r["alpha"])
        body.append(name + " & " + pct(r["seen"]) + " & " + pct(r["unseen"]) + r" \\")

    _cap = (f"WiSE-FT weight ensembling on {j['model']}: the seen/unseen trade-off as a single "
            f"dial ({j['seen_classes']} seen classes, {j['seen_images']:,} images; "
            f"{j.get('unseen_classes', '?')} unseen classes; protocol: {_proto}).")
    if _legacy:
        _cap += " NOTE: legacy file, protocols differ between the two columns."
    if _warn:
        _cap += (" NOTE: this sweep did not pass its own consistency checks and is reported "
                 "for completeness only.")

    # Whether alpha=1 forgets is a question for the data, not a fixed sentence. The
    # 2026-09-06 sweep collapsed to 1.8% unseen against a 1.96% chance floor -- forgetting.
    # The 2026-09-07 sweep holds 16.4%, over eight times chance, while gaining 22.5 points on
    # seen: that is not catastrophic forgetting and the caption must not say it is.
    _a1 = next((r for r in sweep if r["alpha"] == 1.0), None)
    _chance = j.get("unseen_chance") or (1.0 / max(j.get("unseen_classes") or 1, 1))
    # "reproduces the frozen baseline" invited the reader to compare against Table 3's
    # 82.2%, which is a different measurement: this sweep subsamples the seen split to
    # 200 images per class, so its frozen reference is ~59%. Say which baseline.
    # Differences quoted in the text are computed from the unrounded sweep values, so
    # subtracting two rounded cells in this table can miss by 0.1 (e.g. 21.6 - 15.5 = 6.1
    # against the 6.2 in Section 4.5, which is 21.64 - 15.47). Say so once, here, rather
    # than letting a reader read the gap as an arithmetic error.
    _foot = ("$\\alpha=0$ reproduces this sweep's own frozen probe "
             f"({j.get('frozen_probe', 0) * 100:.1f}\\%), validating the interpolation. "
             "That probe is measured on the 200-image-per-class subsample used here, not on "
             "the full seen split of Table~\\ref{tab:seen}. Differences quoted in the text are "
             "computed from the unrounded values, so they may differ by 0.1 from the "
             "difference of two rounded cells here. ")
    if _a1:
        _mult = _a1["unseen"] / _chance if _chance else 0.0
        if _mult < 2.0:
            _foot += ("$\\alpha=1$ is naive fine-tuning and shows catastrophic forgetting, "
                      f"retaining only {_mult:.1f}$\\times$ chance on unseen crops. ")
        else:
            _foot += (f"$\\alpha=1$ is naive fine-tuning; here it still retains "
                      f"{_mult:.1f}$\\times$ chance on unseen crops, so the dial trades "
                      "cross-crop transfer for seen accuracy rather than destroying it. ")
    if _warn:
        # Trim on a word boundary: a mid-word cut reads as a typesetting error rather than
        # as a deliberately abbreviated warning.
        _w = _warn[0].split(" -- ")[0].rstrip(" .")
        _foot += ("The intermediate points are not interpretable here: " + _w + ". ")
    elif _mono:
        _foot += (f"Seen accuracy rises monotonically with $\\alpha$ while unseen accuracy "
                  f"falls, so the dial trades one for the other as intended; "
                  f"$\\alpha={_best['alpha']:.2f}$ maximises their sum.")
    else:
        _foot += (f"$\\alpha={_best['alpha']:.2f}$ maximises the sum of the two columns.")

    write("tab_wiseft.tex", wrap(
        _cap, "tab:wiseft", "lrr",
        "$\\alpha$ & Seen " + UP + " & Unseen zero-shot " + UP + " \\\\", body, _foot))


def tab_edge():
    j = load("edge_quant_benchmark.json")
    if not j:
        return
    body = []
    for _k, d in j["models"].items():
        v = d.get("variants", {})
        g = lambda n, f="p50_ms": v.get(n, {}).get(f)
        fm = lambda x: "---" if x is None else f"{x:.1f}"
        body.append(f"{short(d['model'])} & {d['img_params_M']:.1f} & {fm(g('torch_fp32'))} & "
                    f"{fm(g('onnx_fp32'))} & {fm(g('onnx_int8_dynamic'))} & "
                    f"{fm(g('onnx_int8_static'))} & {g('onnx_fp32', 'size_mb')} & "
                    f"{g('onnx_int8_static', 'size_mb')} \\\\")
    write("tab_edge.tex", wrap(
        "On-device cost of the deployable image encoder (CPU, batch 1, $224\\times224$). "
        "The four latency columns are milliseconds; the final two are megabytes.",
        "tab:edge", "lrrrrrrr",
        "Model & Params (M) & Torch FP32 " + DN + " & ONNX FP32 " + DN + " & "
        "INT8 dyn. " + DN + " & INT8 static " + DN + " & FP32 " + DN + " & "
        "INT8 " + DN + " \\\\", body,
        f"Latency in ms (median of {j['runs']} runs), ONNX Runtime {j.get('ort_version')}. "
        "INT8 makes the three hybrid conv--transformer tiers \\emph{slower} while shrinking them "
        "$\\sim3.5\\times$; the one pure-transformer model here gets faster instead. "
        "The transformer side of that contrast rests on a single row.", wide=True))


def tab_loco():
    j = load("loco_s0_rich.json")
    if not j:
        return
    body = []
    for crop, d in sorted(j["per_crop"].items(), key=lambda kv: -kv[1]["acc"]):
        ci = d.get("ci95", [None, None])
        body.append(f"{crop} & {d['n']:,} & {pct(d['acc'])} & [{pct(ci[0])}, {pct(ci[1])}] \\\\")
    p = j["pooled"]
    body.append("\\midrule")
    body.append(f"\\textbf{{Pooled}} & \\textbf{{{p['n']:,}}} & \\textbf{{{pct(p['acc'])}}} & "
                f"[{pct(p['ci95'][0])}, {pct(p['ci95'][1])}] \\\\")
    # RENAMED. "Leave-one-crop-out" has a standing meaning -- hold a crop out, refit, re-score --
    # and none of it happens here: the descriptor head is training-free, so nothing is left out
    # and nothing is refit. This is a per-crop breakdown of ONE zero-shot run over a common pool.
    write("tab_loco.tex", wrap(
        f"Per-crop zero-shot accuracy on {j['model']} over a common pool of "
        f"{j['n_classes']} classes (chance {pct(j['chance'])}).",
        "tab:loco", "lrrl",
        "Crop & $N$ & Zero-shot " + UP + " & 95\\% CI \\\\", body,
        "No crop is held out and no model is refit here: the descriptor head is training-free, "
        "so this is one zero-shot run broken down by crop. \\emph{Trained} labels crops that sit "
        "in the seen pool of the main experiments. The two hardest crops are both \\emph{trained} "
        "crops, so difficulty does not follow the held-out boundary. The held-out crops here are " "configuration A's three, so this bounds that configuration and not B or C; they "
        "nevertheless average above the trained pool here (19.0\\% against 9.0\\%), so this split "
        "is not adversarially hard. This run covers six of the study's 18 crops, so the "
        "held-versus-trained contrast rests on three crops a side. Measured with the "
        "\\texttt{rich} strategy, "
        "whose prototypes collide (Section~\\ref{sec:strategies}), so the held/trained gap is "
        "itself subject to that confound."))


# ------------------------------------------------------------------------------------------------
# Final-manuscript tables (2026-09-22). Both read paper_numbers.json, which paper_numbers.py
# computes from the released JSONs, so a table and the prose that quotes it share one number.
# ------------------------------------------------------------------------------------------------
AUTH_ROWS = [("bare", "bare"), ("bare80", "bare80"), ("crude", "crude"), ("rich", "rich"),
             ("grounded", "grounded"), ("dclip", "DCLIP"), ("cupl", "CuPL")]


def _numbers():
    p = HERE / "paper_numbers.json"
    if not p.exists():
        raise FileNotFoundError("run docs/paper/paper_numbers.py first")
    return json.loads(p.read_text(encoding="utf-8"))


def tab_authoring():
    N = _numbers()
    cols = [(e, t) for t in ("uncleaned", "clean") for e in "ABC"]
    best = {(e, t): N["configs"][e][t]["best"] for e, t in cols}
    body = []
    for key, name in AUTH_ROWS:
        cells = []
        for e, t in cols:
            v = N["configs"][e][t]["means"][key]
            s = f"{v:.1f}"
            cells.append(f"\\textbf{{{s}}}" if best[(e, t)] == key else s)
        body.append(f"{name} & " + " & ".join(cells) + " \\\\")
    body.append("\\midrule")
    ag = [f"{N['configs'][e][t]['authoring_gain']:.1f}" for e, t in cols]
    sg = [f"{N['configs'][e][t]['size_range_under_best']:.1f}" for e, t in cols]
    body.append("Authoring gain (best $-$ bare) & " + " & ".join(ag) + " \\\\")
    body.append("Encoder-size gain (86.3 $-$ 11.4\\,M) & " + " & ".join(sg) + " \\\\")
    n_cls = [str(N["configs"][e][t]["n_classes"]) for e, t in cols]
    header = ("& \\multicolumn{3}{c}{Full label set} & \\multicolumn{3}{c}{De-duplicated} \\\\\n"
              "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\n"
              "Strategy & " + " & ".join(f"{e} ({n})" for (e, _), n in zip(cols, n_cls)) + " \\\\")
    cap = ("Unseen-crop top-1 accuracy (\\%) by descriptor strategy: mean over the four deployable "
           "encoders, at three nested label spaces (classes in parentheses), on the full and the "
           "de-duplicated label sets. The best strategy in each column is in bold. The authoring gain "
           "is the best strategy minus the class-name default; the encoder-size gain is the change "
           "from the 11.4\\,M to the 86.3\\,M encoder under the best strategy.")
    write("tab_authoring.tex", wrap(cap, "tab:authoring", "lrrrrrr", header, body, wide=True))


def tab_decomp():
    N = _numbers()
    cf, cc = N["configs"]["C"]["uncleaned"], N["configs"]["C"]["clean"]
    body = [
        f"Construction & grounded $\\rightarrow$ grounded, split into sentences & text & "
        f"{cf['split_minus_grounded']:+.1f} & {cc['split_minus_grounded']:+.1f} \\\\",
        f"Text & grounded, split $\\rightarrow$ CuPL & construction & "
        f"{cf['cupl_minus_split']:+.1f} & {cc['cupl_minus_split']:+.1f} \\\\",
        "\\midrule",
        f"Total gap & grounded $\\rightarrow$ CuPL & --- & "
        f"{cf['cupl_minus_grounded']:+.1f} & {cc['cupl_minus_grounded']:+.1f} \\\\",
    ]
    header = ("Factor & Comparison & Held fixed & Full & De-dup. \\\\")
    cap = ("Decomposition of the accuracy gap between source-grounded text and CuPL at configuration C "
           "(51 and 42 classes), in points of mean top-1 over the four deployable encoders. Each row "
           "changes one factor and holds the other fixed; construction and text sum to the total gap "
           "before rounding, so the rounded entries may differ from it by 0.1. "
           "The citation requirement is tested separately by a seeded control "
           "(Section~\\ref{sec:decomp}): removing it changes accuracy by an amount whose 95\\% interval "
           "includes zero.")
    write("tab_decomp.tex", wrap(cap, "tab:decomp", "lllrr", header, body, wide=True))


if __name__ == "__main__":
    for fn in (tab_authoring, tab_decomp, tab_scale_study, tab_abstain, tab_seen, tab_supervised,
               tab_wiseft, tab_edge, tab_loco):
        try:
            fn()
        except Exception as e:
            print(f"[tex] FAILED {fn.__name__}: {type(e).__name__}: {e}")
