"""
Write the verified replacement URLs from SOURCE_CHECKLIST.md back into descriptors/*.json.

WHY THIS EXISTS
---------------
SOURCE_CHECKLIST.md is GENERATED by make_source_checklist.py, which overwrites it. The URL
verification pass was done by hand in that generated file -- 141 entries gained a replacement URL
beside the original -- so the work lived only in an artifact that the next regeneration would erase,
while descriptors/*.json, the source of truth the manuscript actually cites, still held all 141 of
the originals. This moves the verification into the descriptors, after which regenerating the
checklist reproduces the verified state instead of destroying it.

WHAT COUNTS AS A REPLACEMENT
    ### 12. [403 bot-blocked (page exists)] `HELD-OUT` - model-recalled
    <old-url> - <new-url>
The second URL on that line is the verified replacement. Entries with one URL are left alone.

Only the `source_url` changes. The verbatim quote is NOT touched: a quote that no longer appears on
the replacement page is a citation error that needs a human, and silently repointing it would turn a
dead link into fabricated evidence -- the worse failure. Rows whose quote may now be orphaned are
listed at the end for review.

    python scripts/apply_checklist_urls.py            # dry run, prints what would change
    python scripts/apply_checklist_urls.py --write    # apply, then re-run make_source_checklist.py
"""
from __future__ import annotations
import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import config as C

CHECKLIST = C.REPO_ROOT / "docs" / "paper" / "SOURCE_CHECKLIST.md"


def replacements() -> dict[str, str]:
    """{old_url: new_url} for every entry that carries a verified replacement."""
    text = CHECKLIST.read_text(encoding="utf-8", errors="replace")
    out: dict[str, str] = {}
    for entry in re.split(r"\n### ", text)[1:]:
        head = entry.split("- **Cited by:**")[0]
        urls = re.findall(r"<(https?://[^>]+)>", head)
        if len(urls) >= 2 and urls[0] != urls[1]:
            out[urls[0]] = urls[1]
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="apply; otherwise dry run")
    args = ap.parse_args()

    repl = replacements()
    if not repl:
        sys.exit("[fatal] no replacement pairs found in SOURCE_CHECKLIST.md -- nothing to apply.")
    print(f"[checklist] {len(repl)} verified replacement URL(s)")

    changed_fields = 0
    changed_files: Counter = Counter()
    unmatched = set(repl)
    quote_review: list[tuple[str, str, str]] = []

    for path in sorted(C.DESCRIPTORS_DIR.glob("*.json")):
        recs = json.loads(path.read_text(encoding="utf-8"))
        dirty = False
        for rec in recs:
            for fname, field in (rec.get("fields") or {}).items():
                if not isinstance(field, dict):
                    continue
                old = field.get("source_url")
                if old and old in repl:
                    unmatched.discard(old)
                    new = repl[old]
                    if old != new:
                        field["source_url"] = new
                        changed_fields += 1
                        changed_files[path.name] += 1
                        dirty = True
                        if (field.get("verbatim_quote") or "").strip():
                            quote_review.append(
                                (f"{rec.get('crop')}/{rec.get('disease')}", fname, new))
        if dirty and args.write:
            path.write_text(json.dumps(recs, indent=2, ensure_ascii=False) + "\n",
                            encoding="utf-8")

    verb = "updated" if args.write else "would update"
    print(f"[descriptors] {verb} {changed_fields} field(s) across {len(changed_files)} file(s)")
    for name, n in changed_files.most_common():
        print(f"    {name:22s} {n:3d}")
    if unmatched:
        print(f"\n[warn] {len(unmatched)} replacement(s) matched no descriptor field "
              f"(already applied, or the descriptor changed since the checklist was generated):")
        for u in sorted(unmatched)[:10]:
            print(f"    {u[:100]}")

    if quote_review:
        print(f"\n[REVIEW] {len(quote_review)} field(s) kept a verbatim quote while their URL moved.")
        print("         The quote was written against the ORIGINAL page. Confirm it still appears on")
        print("         the replacement, or the citation now reads as fabricated evidence.")
        print("         SOURCE_CHECKLIST.md lists the exact sentence for each under 'Must contain'.")

    if not args.write:
        print("\n[dry run] nothing written. Re-run with --write to apply.")
    else:
        print("\n[next] python scripts/make_source_checklist.py   # regenerate from the descriptors")


if __name__ == "__main__":
    main()
