#!/usr/bin/env python3
"""Emit ready-to-paste chat prompts for the DCLIP and CuPL baselines, one file per crop.

Use this when you want the descriptor registries generated by hand in a chat window instead of
through the API. It spends no credits and needs no key. The prompts are the published question
forms from each paper, with the category slot filled by the same string the code uses for the
`bare` strategy, so the manual route asks for exactly what the API route would.

    python scripts/make_manual_prompts.py
    -> manual_baselines/prompts/dclip_<Crop>.txt   (8 files)
    -> manual_baselines/prompts/cupl_<Crop>.txt    (8 files)

Paste each file into a chat, save the JSON reply to
manual_baselines/replies/<method>_<Crop>.json, then run:

    python scripts/import_manual_baselines.py

TWO DEVIATIONS FROM THE API ROUTE, both worth stating in the paper if these rows are used.
  1. BATCHING. DCLIP and CuPL ask about one category per call; these prompts ask about every
     class of one crop at once, so the model sees sibling classes and may make descriptors more
     discriminative than the per-class methods actually produce. That strengthens the baseline,
     which is the conservative direction for this paper's claim -- if source-grounded text still
     wins against a batched DCLIP, the result is harder to dismiss, not easier.
  2. ONE DRAW. Chat generation gives a single registry, not the three seeds the API route runs.
     Section 4.3 measures a 2.4-point standard deviation between registries, so a manual result
     is a point estimate and any margin under ~2.4 points cannot be read as an effect. Report it
     as a single draw or re-run the prompts two more times into seeds 1 and 2.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import build_descriptors as BD          # noqa: E402
import build_descriptor_baselines as B  # noqa: E402

OUT = ROOT / "manual_baselines" / "prompts"

ORGAN_RULE = """WHICH PLANT PART TO DESCRIBE. The category strings all end in "leaf" because that is
how the classifier names them, but the photographs do not all show leaves. Describe THE PART THE
PHOTOGRAPH ACTUALLY SHOWS for that disease:
  - foliar diseases (leaf spots, blights, mildews, rusts, mosaics, wilts seen as leaf yellowing)
    -> describe the leaf
  - fruit and post-harvest rots (e.g. cigar end rot, green/whisker mould, belly rot, brown rot,
    berry blotch) -> describe the FRUIT, not the leaf
  - cereal head and grain diseases (e.g. head scab, karnal bunt, loose smut) -> describe the HEAD
    or grain
Verified against the image set: cigar end rot is photographed as a blackened banana finger tip and
green mould as a whole mouldy citrus fruit, while Panama disease is photographed as yellowing leaf
blades. Writing "leaf" for a fruit disease would describe something absent from the picture.

ONLY WHAT A CAMERA SEES. No treatment advice, no life cycle, no pathogen taxonomy, and nothing that
needs the plant to be cut open or examined under magnification (internal vascular streaking, for
instance, is not visible in a field photograph)."""

DCLIP_TMPL = """You are answering questions about the visual appearance of categories, for use as
text prompts in an image classifier.

For EACH category below, answer this question:

  Q: What are useful visual features for distinguishing a {{category}} in a photo?
  A: There are several useful visual features to tell there is a {{category}} in a photo.

List them as short noun phrases, each one a single visible feature. Aim for 8-12 phrases per
category, covering colour, lesion shape, texture, margin and distribution.

""" + ORGAN_RULE + """

CATEGORIES ({n}):
{cats}

Reply with ONLY a JSON object, no prose before or after, mapping each category's DISEASE KEY to
its array of phrases. Use the disease keys exactly as given:

{{
{example}
}}
"""

CUPL_TMPL = """You are describing what things look like in photographs, for use as text prompts in
an image classifier.

For EACH category below, write 12 complete sentences describing its appearance in a photo, spread
across these four question forms (3 sentences each):

  1. Describe what a {{category}} looks like in a photo.
  2. Describe a photo of a {{category}}.
  3. What does a {{category}} look like in a photo?
  4. Describe the appearance of a {{category}} in a photo.

Each sentence must stand alone as a description of the visible plant material: colour, lesion
shape, texture, margin, distribution.

""" + ORGAN_RULE + """

CATEGORIES ({n}):
{cats}

Reply with ONLY a JSON object, no prose before or after, mapping each category's DISEASE KEY to
its array of 12 sentences. Use the disease keys exactly as given:

{{
{example}
}}
"""


HEADER = """================================================================================
 DESCRIPTOR BASELINE PROMPTS  --  {nblocks} blocks, {ncls} classes, 2 methods
================================================================================
Paste ONE block at a time into a fresh chat. Do not paste the whole file at once:
{ncls} classes x 12 sentences is far more than one reply can hold, and a truncated
reply silently loses classes.

For each block, save the JSON reply to:
    manual_baselines/replies/<method>_<Crop>.json
e.g. block 1 -> manual_baselines/replies/dclip_Banana.json

Then check coverage without writing anything:
    python scripts/import_manual_baselines.py --check
and when every block is in:
    python scripts/import_manual_baselines.py
    python scripts/evaluate.py --exp C --strategies bare80 dclip cupl --heavy

THE TWO METHODS DIFFER AND ARE NOT INTERCHANGEABLE:
  dclip = short noun PHRASES   ("raised corky lesions", "yellow halo")
  cupl  = complete SENTENCES   ("Citrus canker on an orange leaf appears as ...")
A dclip block answered with sentences, or a cupl block answered with phrases, is
the wrong method and will not reproduce the published baseline.
================================================================================

"""

BLOCK = """

================================================================================
 BLOCK {i} of {n}   --   {method}   --   {crop}   ({k} classes)
 save reply as: manual_baselines/replies/{method}_{crop}.json
================================================================================

{body}
"""


def main() -> int:
    by_crop = BD.classes_from_manifest("heldout")
    OUT.mkdir(parents=True, exist_ok=True)
    n_cls = sum(len(v) for v in by_crop.values())
    blocks, total = [], 0

    for crop in sorted(by_crop):
        diseases = sorted(by_crop[crop])
        cats = "\n".join(f'  {d}  ->  "{B.category_of(crop, d)}"' for d in diseases)
        ex = ",\n".join(f'  "{d}": ["...", "..."]' for d in diseases[:2])
        if len(diseases) > 2:
            ex += ",\n  ... one entry for every disease key above"
        for method, tmpl in (("dclip", DCLIP_TMPL), ("cupl", CUPL_TMPL)):
            body = tmpl.format(n=len(diseases), cats=cats, example=ex)
            (OUT / f"{method}_{crop}.txt").write_text(body, encoding="utf-8", newline="\n")
            total += 1
            blocks.append((method, crop, len(diseases), body))
        print(f"  {crop:9s} {len(diseases):2d} classes -> dclip_{crop}.txt, cupl_{crop}.txt")

    combined = HEADER.format(nblocks=len(blocks), ncls=n_cls)
    for i, (method, crop, k, body) in enumerate(blocks, 1):
        combined += BLOCK.format(i=i, n=len(blocks), method=method, crop=crop, k=k, body=body)
    all_path = OUT.parent / "ALL_PROMPTS.txt"
    all_path.write_text(combined, encoding="utf-8", newline="\n")

    print(f"\n{total} individual prompt files in {OUT}")
    print(f"combined: {all_path}  ({len(combined):,} chars, {len(blocks)} blocks)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
